### ISSUE TITLE
separators and modifiers

### ISSUE THREAD

**Issue by justLuiz** [muratgozel/node-calver#1]
first thanks for writing this library

I would like to know if you have any plans to support modifiers `dev`, `alpha`
and support additional separators to the dot `.`, like `-` or `_`
or simply allow identifiers together, like YYYY0M

let me know if you need more information or prs about it

**Comment by muratgozel** [comment]
The only feature missing right now is the `MODIFIER` tags such as `dev.1` or `alpha.201`. I'll add it to the API as soon as I have time. I think API would be similar to:
```js
const calver = new Calver('YY.MM.MICRO-MODIFIER', '20.8.123-alpha1')
calver.inc('modifier')
calver.get() === '20.8.123-alpha2'
```
And if I want to switch to another pre-release tag:
```js
calver.inc('modifier', 'beta')
calver.get() === '20.8.123-beta1'
```
What do you think?

**Comment by muratgozel** [comment]
Modifier tags are now supported as of release 21.1.0. The api is not exactly the same as I mentioned above but similar. Please see readme.
