### ISSUE TITLE
Do you have a plan to support timezone? 

### ISSUE THREAD

**Issue by banyan** [muratgozel/node-calver#12]
Currently, it's fixed as UTC. do you have a plan to support timezone? 
I am willing to create a PR, but it's better to confirm before I do that.

**Comment by muratgozel** [comment]
Hey banyan, thanks for bringing this up. I think this would be an essential feature for this library. An option to specify different timezones or an option like useLocalTime... Please make a PR if you have time for it 🙏

For implementation I would add a property to the `Calver` class such as `timezone` or `useLocalTime` and then we would do:
```js
import calver from 'calver';

calver.timezone = 'UTC'
// or
calver.useLocalTime = true // should be off by default for backward compatibility
```
if that makes sense to you also...

**Comment by banyan** [comment]
Thanks. Both API makes sense to me. Let me try with that.

**Comment by muratgozel** [comment]
awesome contribution @banyan thank you very much!

**Comment by banyan** [comment]
You're welcome! Thanks too!
