### ISSUE TITLE
Reset increments

### ISSUE THREAD

**Issue by aazbeltran** [muratgozel/node-calver#3]
Exists an issue where when you are using the major, minor and micro, and you increment minor o major (as example), the lower types must be reset to zero, but those types keep their values.

Example:
```javascript
const calver=new Calver('YYYY.MINOR.MICRO','2020.0.0');
calver.inc('micro');
console.log(calver.get());
// 2020.0.1
calver.inc('minor');
console.log(calver.get());
// 2020.1.1
// In this case must be 2020.1.0
// And the year must be 2021
```

**Comment by muratgozel** [comment]
It looks like a bug. However, the year stay same if you specify a semantic tag (such as minor) since the developer may be just patching an existing release. Like patching a software which released on 2011 and then the full version number will be something like 2011.4.26783

Will send a fix soon.

**Comment by aazbeltran** [comment]
I'm working on it, I'll send you the fix today 😀 Have a nice day!

**Comment by muratgozel** [comment]
Will be glad for it, thanks. 🎉

**Comment by aazbeltran** [comment]
The PR is done, I added some fixes and a parameter to keep the specified date, can you check this please?

**Comment by aazbeltran** [comment]
Hi @muratgozel , how are you? 😀  Do you had the chance to check the code?

**Comment by muratgozel** [comment]
I'll refactor code shortly. I have to implement the support for some development tags and make to code more maintainable.

**Comment by muratgozel** [comment]
Shipped. 🐬

**Comment by aazbeltran** [comment]
Hey dude, good job! Tomorrow I will review the changes in detail, I think there will be breaking changes... Have an excellent week! Respect for the great amount of JS libraries you maintain. Greetings from Mexico 🤟🏿
