### ISSUE TITLE
inc behavior unclear

### ISSUE THREAD

**Issue by schelv** [muratgozel/node-calver#7]
Hi!
It is not exactly clear to me how `calver.inc(format ,version , 'calendar')` is supposed to work.
For example the following test cases scenarios:
```
assert.strictEqual(calver.inc('yyyy.mm.patch', '2020.6.1', 'calendar'), '2021.1.0')
assert.strictEqual(calver.inc('yyyy.mm.patch', '2021.1.0', 'calendar'), '2021.1.0')
```
The first line I would expect that the calendar is updated to the current date, and the patch number is reset.
For the second line I would expect to get some kind of error, because the inc doesn't actually increment anything.

Is this supposed to happen?

**Comment by muratgozel** [comment]
Hi,

Thanks for bringing up this issue because I need community support about this. There are use cases with formats such as `major.yyyy.mm`. When you take semantic tags to the front, resetting them to zero when calendar tags are updated may not be desired. The version `1.2020.6` will become `0.2021.1` for example. Therefore I'm not clear about resetting semantic tags when calendar tags are updated. I'm open to debates.

About the second line: Users will mostly know if the version will be updated before executing the `.inc` method but the library may throw an error as you said if the version stays same.

**Comment by schelv** [comment]
That's a good point.

On second thought, I think the patch number in the first example isn't really used as a semantic tag.
The use is to distinguish multiple releases within the timeframe.
The timeframe depends on the used format. For example `.inc('yyyy.patch', '2021.0', 'calendar')` would become `2021.1`

Maybe another type of calendar tag is needed for this use case.
That would make it possible to update the calendar version without messing up any semantic version.

**Comment by muratgozel** [comment]
I also have the following in my mind:

Place a question mark at the end of the semantic tag while specifying a format like `major?.yyyy.mm`. The question mark indicates that that tag is **lazy** and won't be modified on calendar increments. It can only be incremented by sending `major` as inc level.

As you said, we can also define more tags to make this work but naming those tags is hard. It will become strange to all of us. But still, open to suggestions for those kinds of tags.

**Comment by schelv** [comment]
And what should happen when there are multiple calendar increments in the same month?

**Comment by muratgozel** [comment]
Should throw an error. If someone chose a format containing only `...yyyy.mm...` calendar tags then it means "we make calendar updates one per month at most".

**Comment by muratgozel** [comment]
@schelv hello hello again, sorry for returning late about this. i made the library a bit more opinionated. regarding this case, i have implemented an expression that checks if the version has changed or not after `.inc` called. So if you run your example above again, it will **throw**. 

Closing this case now but please let me know if you need any help in this.
