### ISSUE TITLE
Semantic calendar bumps aren't working

### ISSUE THREAD

**Issue by kherock** [muratgozel/node-calver#8]
The last refactor has a major regressed where the feature discussed in #2 is no longer possible.

```console
calver.inc('YY.MM.MINOR', '21.1.0', 'calendar.minor')
Uncaught:
Error: The second tag of the level should be a modifier tag. You specified "MINOR" as the second tag and "CALENDAR" as the first tag.
```

It seems like this feature was explicitly removed based on the v21.11.0 changelog

> Second level might only be a modifier

Just as a reminder, I gave a rationale for why this feature is helpful here: https://github.com/muratgozel/node-calver/issues/2#issuecomment-859537917.

**Comment by muratgozel** [comment]
Hey @kherock 

You have to be specifying the level of the release in your codebase, don't you?

**Comment by kherock** [comment]
I'm not sure what you mean, in my case I don't have `major` releases. Every month or so when I go to make a release, I do a version bump to the current date. Sometimes I'll end up with more than one release in a month, which ends up incrementing versions resembling `21.12.1`, `21.12.2`, etc. This is the whole reason I'm using CalVer - I don't want to think about the semantics of a major vs minor vs patch bump since the software I'm releasing doesn't have a public API.

The most important thing that I want out of this library is that it saves me from teaching my release pipeline how to increment the version when the date hasn't changed substantially. I don't see a simple way for me to increment my version number without my pipeline being aware of the date on the last release.

```console
> const fmt = 'YY.MM.patch'
> calver.inc(fmt, '21.12.0', 'calendar')
'21.12.0' // doesn't return a new version number

> calver.inc(fmt, '21.11.0', 'patch')
'21.11.1' // version number has an incorrect month

> calver.inc(fmt, calver.inc(fmt, '21.11.0', 'calendar'), 'patch')
'21.12.1' // skipped version '21.12.0'
```

**Comment by muratgozel** [comment]
I understand. Yes, I intentionally ignored this use case. In the current implementation, the library is more flexible and have the potential to cover various use cases. Your use case can be implemented as:
```js
calver.inc(fmt, '21.12.0', 'calendar', {fallbackLevelOrSecondaryLevel: 'semantic'})
```

I'll be asking to use the previous release until I implement this.

**Comment by muratgozel** [comment]
@kherock hello hello again, sorry for returning late about this. i made the library a bit more opinionated. regarding this case, the lib supports specifying calendar and semantic tags again. so you can safely use the example you gave above. it will try to increase calendar portion and after that the semantic portion increase/reset depending on the calendar portion updated or not.

Closing this case now but please let me know if you need any help in this.
